"use client";
import {useEffect,useMemo,useState} from "react";
type Scores={staticAim:number;flick:number;movement:number;recoil:number;transfer:number;crosshair:number;clearing:number;firstShot:number;flow:number};
type SavedCheck={id:number;player:string;ign:string;role:string;device:string;evaluator:string;notes:string;scores:Scores;deductions:number;total:number;rating:string;date:string};
const initialScores:Scores={staticAim:0,flick:0,movement:0,recoil:0,transfer:0,crosshair:0,clearing:0,firstShot:0,flow:0};
function NumericScore({value,max,onChange}:{value:number;max:number;onChange:(n:number)=>void}){return <div className="score-control"><input aria-label={`Score out of ${max}`} type="number" min="0" max={max} value={value} onChange={e=>onChange(Math.min(max,Math.max(0,Number(e.target.value))))}/><span>/ {max}</span></div>}
function ratingFor(total:number){if(total>=90)return{name:"Elite Mechanics",action:"Strong main-roster candidate",tone:"elite"};if(total>=80)return{name:"Advanced",action:"Main roster or final trial",tone:"advanced"};if(total>=70)return{name:"Competitive",action:"Academy or substitute consideration",tone:"competitive"};if(total>=60)return{name:"Developing",action:"Needs coaching and another trial",tone:"developing"};return{name:"Not Ready",action:"Continue individual training",tone:"not-ready"}}
export default function Home(){
 const[scores,setScores]=useState<Scores>(initialScores);const[player,setPlayer]=useState("");const[ign,setIgn]=useState("");const[role,setRole]=useState("Duelist");const[device,setDevice]=useState("");const[evaluator,setEvaluator]=useState("");const[notes,setNotes]=useState("");const[deductions,setDeductions]=useState(0);const[saved,setSaved]=useState<SavedCheck[]>([]);const[showHistory,setShowHistory]=useState(false);const[toast,setToast]=useState("");
 useEffect(()=>{const data=localStorage.getItem("tru-mechanics-results");if(data)setSaved(JSON.parse(data))},[]);
 const sections=useMemo(()=>({static:scores.staticAim,flick:scores.flick,movement:scores.movement,recoil:scores.recoil+scores.transfer,angles:scores.crosshair+scores.clearing+scores.firstShot+scores.flow}),[scores]);const raw=Object.values(sections).reduce((a,b)=>a+b,0);const total=Math.max(0,raw-deductions);const rating=ratingFor(total);const updateScore=(key:keyof Scores,value:number)=>setScores(s=>({...s,[key]:value}));
 function clearForm(){setScores(initialScores);setPlayer("");setIgn("");setRole("Duelist");setDevice("");setNotes("");setDeductions(0)}
 function saveResult(){if(!ign.trim()){setToast("Add the player's IGN before saving.");return}const item:SavedCheck={id:Date.now(),player,ign,role,device,evaluator,notes,scores,deductions,total,rating:rating.name,date:new Date().toLocaleString()};const next=[item,...saved];setSaved(next);localStorage.setItem("tru-mechanics-results",JSON.stringify(next));setToast("Assessment saved on this device.");setTimeout(()=>setToast(""),2800)}
 function loadResult(item:SavedCheck){setPlayer(item.player);setIgn(item.ign);setRole(item.role);setDevice(item.device);setEvaluator(item.evaluator);setNotes(item.notes);setScores(item.scores);setDeductions(item.deductions);setShowHistory(false);window.scrollTo({top:0,behavior:"smooth"})}
 function deleteResult(id:number){const next=saved.filter(s=>s.id!==id);setSaved(next);localStorage.setItem("tru-mechanics-results",JSON.stringify(next))}
 return <main><header className="topbar"><div className="brand"><div className="mark">T</div><div><strong>TRU LEGACY</strong><span>PLAYER DEVELOPMENT</span></div></div><div className="header-actions"><button className="ghost" onClick={()=>setShowHistory(!showHistory)}>Results <b>{saved.length}</b></button><button className="ghost" onClick={()=>window.print()}>Print report</button></div></header>
 <section className="intro"><div><p className="eyebrow">VALORANT MOBILE • TRAINING GROUND</p><h1>Mechanics Check</h1><p className="subtitle">A standardized 100-point evaluation for raw aim, movement, recoil control, and angle discipline.</p></div><div className="test-meta"><span>05 drills</span><span>~30 min</span><span>03 attempts</span></div></section>
 {showHistory&&<section className="history panel"><div className="panel-title"><div><small>SAVED LOCALLY</small><h2>Player results</h2></div><button className="close" onClick={()=>setShowHistory(false)}>×</button></div>{saved.length===0?<div className="empty">No assessments saved yet.</div>:<div className="history-list">{saved.map(item=><article key={item.id}><div className={`mini-score ${ratingFor(item.total).tone}`}>{item.total}</div><div className="history-name"><strong>{item.ign}</strong><span>{item.player||"Unnamed player"} • {item.role}</span></div><div className="history-rating"><strong>{item.rating}</strong><span>{item.date}</span></div><button onClick={()=>loadResult(item)}>Open</button><button className="danger" onClick={()=>deleteResult(item.id)}>Delete</button></article>)}</div>}</section>}
 <div className="workspace"><div className="form-column"><section className="panel player-panel"><div className="section-number">00</div><div className="section-head"><h2>Player information</h2><p>Identify the candidate and testing setup.</p></div><div className="field-grid"><label>PLAYER NAME<input value={player} onChange={e=>setPlayer(e.target.value)} placeholder="Full name"/></label><label>IN-GAME NAME *<input value={ign} onChange={e=>setIgn(e.target.value)} placeholder="Player IGN"/></label><label>PRIMARY ROLE<select value={role} onChange={e=>setRole(e.target.value)}><option>Duelist</option><option>Initiator</option><option>Controller</option><option>Sentinel</option><option>Flex</option></select></label><label>DEVICE / FPS<input value={device} onChange={e=>setDevice(e.target.value)} placeholder="e.g. iPhone 15 • 120 FPS"/></label></div></section>
 <Drill n="01" title="Static Headshot Accuracy" description="30 stationary targets • medium distance • Vandal • one-tap only" score={sections.static}><ScoreRow title="Average result" hint="28–30 = 20 • 25–27 = 17 • 22–24 = 14 • 19–21 = 10 • 15–18 = 6" value={scores.staticAim} max={20} set={v=>updateScore("staticAim",v)}/></Drill>
 <Drill n="02" title="Flick & Target Switching" description="Timed bot challenge • medium difficulty • three official attempts" score={sections.flick}><ScoreRow title="Average bots eliminated" hint="27–30 = 20 • 24–26 = 17 • 21–23 = 14 • 18–20 = 10 • 14–17 = 6" value={scores.flick} max={20} set={v=>updateScore("flick",v)}/></Drill>
 <Drill n="03" title="Strafe–Stop–Shoot" description="20 targets • alternate directions • score clean stops, not speed" score={sections.movement}><ScoreRow title="Movement discipline" hint="Clean stop + headshot = 1 • body/correction = 0.5 • moving miss = 0" value={scores.movement} max={20} set={v=>updateScore("movement",v)}/></Drill>
 <Drill n="04" title="Recoil & Spray Transfer" description="20-meter full spray followed by three-bot continuous transfer" score={sections.recoil}><ScoreRow title="Recoil control" hint="Tight grouping and minimal vertical escape" value={scores.recoil} max={10} set={v=>updateScore("recoil",v)}/><ScoreRow title="Spray transfer" hint="Clean, controlled transfer across three targets" value={scores.transfer} max={10} set={v=>updateScore("transfer",v)}/></Drill>
 <Drill n="05" title="Angle Clearing" description="Same map, site, starting point, and entry course for every candidate" score={sections.angles}><ScoreRow title="Head-level crosshair" hint="Crosshair remains aligned to likely head position" value={scores.crosshair} max={5} set={v=>updateScore("crosshair",v)}/><ScoreRow title="Angle isolation" hint="Clears angles individually without overexposing" value={scores.clearing} max={5} set={v=>updateScore("clearing",v)}/><ScoreRow title="First-shot accuracy" hint="Accurate and controlled initial shot" value={scores.firstShot} max={5} set={v=>updateScore("firstShot",v)}/><ScoreRow title="Movement & completion" hint="Smooth pathing with efficient completion time" value={scores.flow} max={5} set={v=>updateScore("flow",v)}/></Drill>
 <section className="panel deductions"><div><small>PENALTIES</small><h2>Deductions</h2><p>Apply for moving shots, excess bullets, or exposed uncleared angles.</p></div><div className="deduction-input"><span>−</span><input type="number" min="0" max="100" value={deductions} onChange={e=>setDeductions(Math.max(0,Number(e.target.value)))}/><b>PTS</b></div></section>
 <section className="panel notes"><div className="field-grid"><label>EVALUATOR<input value={evaluator} onChange={e=>setEvaluator(e.target.value)} placeholder="Coach / staff name"/></label></div><label>COACHING NOTES<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Consistency, control, movement discipline, coachability, device limitations…"/></label></section></div>
 <aside className="summary panel"><small>LIVE ASSESSMENT</small><div className="identity"><h2>{ign||"Player IGN"}</h2><span>{role}</span></div><div className={`score-ring ${rating.tone}`} style={{"--progress":`${Math.min(100,total)*3.6}deg`} as React.CSSProperties}><div><strong>{total}</strong><span>/ 100</span></div></div><div className={`rating ${rating.tone}`}><strong>{rating.name}</strong><span>{rating.action}</span></div><div className="breakdown"><Breakdown name="Static aim" value={sections.static}/><Breakdown name="Flicking" value={sections.flick}/><Breakdown name="Movement" value={sections.movement}/><Breakdown name="Recoil" value={sections.recoil}/><Breakdown name="Angles" value={sections.angles}/></div>{deductions>0&&<div className="penalty-line"><span>Deductions</span><strong>−{deductions}</strong></div>}<button className="primary" onClick={saveResult}>Save assessment</button><button className="secondary" onClick={clearForm}>New player</button><p className="save-note">Results are stored on this device.</p></aside></div>{toast&&<div className="toast">{toast}</div>}<footer>TRU LEGACY <span>•</span> VALORANT MOBILE PLAYER DEVELOPMENT</footer></main>}
function Drill({n,title,description,score,children}:{n:string;title:string;description:string;score:number;children:React.ReactNode}){return <section className="panel drill"><div className="section-number">{n}</div><div className="drill-body"><div className="section-head"><div><h2>{title}</h2><p>{description}</p></div><div className="section-score"><strong>{score}</strong><span>/20</span></div></div>{children}</div></section>}
function ScoreRow({title,hint,value,max,set}:{title:string;hint:string;value:number;max:number;set:(n:number)=>void}){return <div className="score-row"><div><strong>{title}</strong><p>{hint}</p></div><NumericScore value={value} max={max} onChange={set}/></div>}
function Breakdown({name,value}:{name:string;value:number}){return <div><span>{name}</span><div className="bar"><i style={{width:`${value*5}%`}}/></div><strong>{value}<small>/20</small></strong></div>}
